### ISSUE TITLE
TinyMCE Custom style formats CSS - UIkit responsive classes need specific treatment

### ISSUE THREAD

**Issue by chriswthomson** [processwire/processwire-issues#1756]
If a UIkit responsive class is used in this config field, any CSS specified is not applied as the @ needs escaped.

For example:

```css
#Blocks ul.uk-list.uk-column-1-2@s { padding-left: 20px; } /* 2-Column List */
#Blocks ul.uk-list.uk-column-1-3@s { padding-left: 20px; } /* 3-Column List */
```

The padding left is not used. However if I add the backslash

```css
#Blocks ul.uk-list.uk-column-1-2\@s { padding-left: 20px; } /* 2-Column List */
#Blocks ul.uk-list.uk-column-1-3\@s { padding-left: 20px; } /* 3-Column List */
```

It works, but any subsequent elements are added with the class with the backslash included.

The @ needs a backslash prepended as part of the code that converts this config fields value into the actual CSS used.

Cheers,

Chris
