### ISSUE TITLE
Admin thumbnail problems if SVG does not have width and height attributes

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#1810]
### Short description of the issue

SVG images can have width and height attributes but it's not compulsory that they do. When SVG files without width and height attributes are uploaded to an images field there are problems with the thumbnail display.

In list view mode the display is okay but in square mode the image often does not fill the available space and in proportional mode the thumbnail width can collapse to zero, for example when the width slider is used.

Screencast:

![svg1](https://github.com/processwire/processwire-issues/assets/1538852/a0696897-846e-4906-ad56-682a807c03c8)

PW does know information about the width, height and ratio of each SVG, which is extracted when the image is first uploaded:

![2023-09-13_202824](https://github.com/processwire/processwire-issues/assets/1538852/4d0bad4c-7df8-4348-9b91-c7f64044618d)

It seems like there should be some way to use the width/height/ratio information to avoid the thumbnail problems.

Note: extracting the width/height/ratio from SVGs without width and height attributes currently depends on ImageMagick but I have an idea of how this can be done without it, which I'll discuss in a separate issue soon.

A couple of demo SVG files:
![google-2015](https://github.com/processwire/processwire-issues/assets/1538852/54cf4ced-8abb-437f-928f-474c8e6f34db)
![Microsoft_logo_(2012)](https://github.com/processwire/processwire-issues/assets/1538852/81565b11-4579-4b5d-8d75-807b25964cc2)

### Setup/Environment

* ProcessWire version: 3.0.226

**Comment by Toutouwai** [comment]
This fix for this is simpler than I thought it would be.

I made a modification to InputfieldImage::renderItem() at [line 662](https://github.com/processwire/processwire/blob/2ea60ee7d545f347a68bcfa5f6c4507e092f8aed/wire/modules/Inputfield/InputfieldImage/InputfieldImage.module#L662):

```php
$aspect = $pagefile->ratio < 1 ? 'portrait' : 'landscape';
$out = $this->getTooltip($pagefile) . "
    <div class='gridImage__overflow $aspect'>
        $thumb[markup]
    </div>
";
```

And added some extra SCSS:

```css
.InputfieldImageList {
    .gridImage__overflow.landscape {
        img { height: 100%; }
    }
    .gridImage__overflow.portrait {
        img { width: 100%; }
    }
}

.InputfieldImageList[data-ragged="1"] {
    .gridImage__overflow.portrait {
        img { width: auto; height: 100%; }
    }
}
```

Now it looks good to me. I mean, there's a lot of cropping on some logos in square mode due to their aspect ratios but it's consistent with how photographic images are displayed.

![svg2](https://github.com/processwire/processwire-issues/assets/1538852/7e57880b-4511-411f-95d1-516d649e1677)
