### ISSUE TITLE
Use main theme color for text selection

### ISSUE THREAD

**Issue by daun** [processwire/processwire-issues#2092]
The new default admin theme doesn't override UiKit's selection color, resulting in all text selections using the default UiKit blue.

![Image](https://github.com/user-attachments/assets/f6170e98-c6cb-4516-ac29-735a2ba93c10)

One solution would be to use the main color as selection color. The other would be to reset this and leave it to the browser to apply a system color.

```css
::selection {
  background: var(--main-color);
  color: #fff;
  text-shadow: none;
}
```
