### ISSUE TITLE
Admin CSS rule creates misalignment of fieldset inputfield

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#305]
### Short description of the issue

The core admin themes (default and Reno) contain the following CSS rule:

```css
.InputfieldForm .Inputfields .Inputfields>.Inputfield:last-child, 
.InputfieldForm .Inputfields>.Inputfield>.InputfieldContent>*:last-child {
    margin-bottom: 0;
}
```

The first selector in this rule causes a slight but visible misalignment in the following situation:

- fieldset has column width less than 100%
- fieldset contains inputfields on the bottom row with column width less than 100% (i.e. the bottom row contains more than one inputfield)

This is a minor issue but I'm working on a fieldset-related module and this misalignment becomes problematic there. 

### Screenshot

![2017-07-02_180155](https://user-images.githubusercontent.com/1538852/27767615-1f179752-5f51-11e7-9299-00e112d7bb49.png)

### Optional: Suggestion for a possible fix

Remove the first selector in the CSS rule, so it becomes:

```css
.InputfieldForm .Inputfields>.Inputfield>.InputfieldContent>*:last-child {
    margin-bottom: 0;
}
```
I tested this and couldn't observe any ill effects from removing that part of the rule, within fieldsets or otherwise.

### Setup/Environment

* ProcessWire version: 3.0.65
