### ISSUE TITLE
AdminThemeUikit: input widths forced to 100%

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#478]
### Short description of the issue

AdminThemeUikit has CSS that force inputs (text, number, email, maybe others) to 100% width. The previous core admin themes (Default and Reno) did not do this except for specific situations (InputfieldMaxWidth class, description field, etc). This allowed input widths to be determined by the size attribute.

The CSS in AdminThemeUikit prevents the "Input Size" setting for integer fields from working.
![2018-01-17_200342](https://user-images.githubusercontent.com/1538852/35030114-c5602972-fbc2-11e7-8bc8-9ed827ae7bbd.png)

Default:
![2018-01-17_200405](https://user-images.githubusercontent.com/1538852/35030129-d072f0f6-fbc2-11e7-8d74-33b7929e4088.png)

Uikit:
![2018-01-17_200434](https://user-images.githubusercontent.com/1538852/35030139-d9716ce6-fbc2-11e7-9cb2-26189d7ea382.png)

It also pushes the units text to the next line in image field settings.

Default:
![2018-01-17_201908](https://user-images.githubusercontent.com/1538852/35030446-d36e4d04-fbc3-11e7-9bf5-bc2ad3b42bdb.png)

Uikit:
![2018-01-17_201847](https://user-images.githubusercontent.com/1538852/35030453-da3861b0-fbc3-11e7-9aab-8262d22114b8.png)

And generally it looks a bit weird having an input that expects one or two digits stretching across the whole interface:
![2018-01-17_200946](https://user-images.githubusercontent.com/1538852/35030236-244ee978-fbc3-11e7-8a53-af46658a8f7b.png)

On the topic of inputs: many of the PW settings inputs that expect an integer use a text type input. Would it not be better to use number inputs for these settings? That would help to prevent the accidental typing of invalid settings.

### Setup/Environment

* ProcessWire version: 3.0.88

**Comment by rolandtoth** [comment]
Just in case, have you tried it with AOS module turned off?

**Comment by Toutouwai** [comment]
> Just in case, have you tried it with AOS module turned off?

Yes, it's not related to AOS.

The CSS responsible is in uikit.pw.min.css
```css
.Inputfield input[type=date]:not(.uk-input), .Inputfield input[type=datetime]:not(.uk-input), .Inputfield input[type=email]:not(.uk-input), .Inputfield input[type=number]:not(.uk-input), .Inputfield input[type=text]:not(.uk-input), .Inputfield input[type=url]:not(.uk-input) {
...
width: 100%;
...
}
```
And those `:not(.uk-input)` parts are a bit strange too, because
