### ISSUE TITLE
ProcessModule: CSS rules affect AdminDataTable column widths for module configs

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#568]
### Short description of the issue

In the module config for ProcessProfile, the "What fields can a user edit in their own profile?" table looks like this:

![2018-04-19_204437](https://user-images.githubusercontent.com/1538852/38981045-81cec892-4412-11e8-87b3-76676f4f1e23.png)

Notice that the middle column is squashed to a narrow width.

The cause is the following CSS in wire\modules\Process\ProcessModule\ProcessModule.css

```css
table.AdminDataList td:first-child,
table.AdminDataList th:first-child {
	width: 30%; 
	vertical-align: top; 
}
/* ... */
table.AdminDataList td:last-child {
	width: 70%;
}
```

So that means that all the table width is consumed by the first and last columns, leaving no available width for any other columns. Plus the 30%/70% split probably doesn't suit a lot of module configs that might be using an AdminDataTable.

I think maybe these CSS rules are intended only for the modules list, in which case they need some more specificity, e.g. `#modules_form table.AdminDataList td:first-child` etc...

### Setup/Environment

* ProcessWire version: 3.0.98
