### ISSUE TITLE
Focusarea has wrong 10px offset in NarrowMode

### ISSUE THREAD

**Issue by phlppschrr** [processwire/processwire-issues#728]
### Short description of the issue
The grey overlay is shifted by 10px in narrow mode (`.InputfieldImageNarrow` class set) 

See screenshot:
<img width="406" alt="focusarea-css-bug" src="https://user-images.githubusercontent.com/2077403/47022349-92365c80-d15d-11e8-8044-c3bb804079e0.png">

Adding a css overwrite fixes the issue:
```css
.InputfieldImageEditAll.InputfieldImageNarrow .gridImage__overflow > .focusArea {
    top: 0;
    left: 0;
}
```
