### ISSUE TITLE
AdminThemeUikit: text cut off inside Lister selects

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#805]
### Short description of the issue

Text is cut off at the bottom in select elements within Lister in AdminThemeUikit, Windows Chrome.

![2019-02-04_153524](https://user-images.githubusercontent.com/1538852/52187497-afb93e80-2892-11e9-9b6e-107470971be8.png)

In AdminThemeUikit there is the following CSS rule:

```css
.uk-checkbox, .uk-input, .uk-radio, .uk-select, .uk-textarea {
    font: inherit
}
```

This causes the element's line-height to be inherited from the parent element. In the case of Lister (and InputfieldSelector too I guess) the line-height of the parent `li.selector-row` is 1em, which is too small to fully include the descenders within the select text.

### Setup/Environment

* ProcessWire version: 3.0.125
