### ISSUE TITLE
AdminThemeUikit: browser style is lost for disabled select option

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#850]
### Short description of the issue

Browsers generally give disabled options in a select a lighter grey colour so they can be distinguished from selectable options. The browser disabled style is intact in AdminThemeDefault and AdminThemeReno but is overridden in AdminThemeUikit.

AdminThemeDefault:
![2019-04-12_161611](https://user-images.githubusercontent.com/1538852/56012160-485eb580-5d3f-11e9-9017-076f228f7ee3.png)

AdminThemeUikit:
![2019-04-12_161547](https://user-images.githubusercontent.com/1538852/56012173-501e5a00-5d3f-11e9-8c8d-16f5261b7f2b.png)

The rule responsible:

```css
.uk-select:not([multiple]):not([size]) option {
    color: #444;
}
```

Not sure what this rule is needed for (removing it made no difference that I could notice), but if it is needed then disabled options should excluded from it:

```css
.uk-select:not([multiple]):not([size]) option:not([disabled]) {
    color: #444;
}
```

### Setup/Environment

* ProcessWire version: 3.0.129
