### ISSUE TITLE
Menu spinner is wonky

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-issues#874]
### Short description of the issue

The spinner that appears when submenus are AJAX-loading is wonky:

![spinner](https://user-images.githubusercontent.com/1538852/57439194-982a9100-7299-11e9-8cd5-cf8a2cb513ae.gif)

### Suggestion for a possible fix

Extra CSS for spinner element:

```css
.ui-menu .ui-menu-item a i.fa.fa-spinner { 
    padding: 0; 
    margin-right: 4px;
}
```

![spinner2](https://user-images.githubusercontent.com/1538852/57439436-1f780480-729a-11e9-9a6a-e46ba03ee086.gif)

### Setup/Environment

* ProcessWire version: 3.0.131
